### ISSUE TITLE
pthread_create exist failed

### ISSUE THREAD

**Issue by stanathong** [hengli/camodocal#29]
I have tried to compile camodocal on Ubuntu14.04. As I used VirtualBox, I have problem with CUDA so I didn't CUDA on my machine. 

I compiled the sourcecode and it showed 'Configuring done', 'Generating done'.
![build result](https://cloud.githubusercontent.com/assets/8308557/10268769/1361af60-6abb-11e5-879f-2941c0235710.png)

Anyway, the errors I found in CMakeError.log are
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
and
/usr/bin/ld: cannot find -lpthreads
And I couldn't get any executables in my build folder.

I'm not sure if this is related to no CUDA intalled (but as I understood, the compilation of CamOdoCal without CUDA has be solved).

Any comments or suggestions to fix this issue would be greatly appreciate. Thank you very much.

**Comment by ahundt** [comment]
That's not an issue with CUDA. It is an issue with pthreads during the initial cmake configuration step. In fact that's a problem with the check that pthreads is set up correctly on your ubuntu installation. That's why it says "CheckSymbolExists".  [Here are the docs for that component of cmake](https://cmake.org/cmake/help/v3.3/module/CheckSymbolExists.html)

If there is a problem with pthreads, it may be due to an issue with [code that should look like this](https://stackoverflow.com/questions/5395309/cmake-and-threads). If you go through the cmake scripts you can make sure that it is correct.

You may want to try googling and stackoverflow.com because this problem doesn't seem specific to camodocal.

**Comment by ahundt** [comment]
This seems like it may be related: https://stackoverflow.com/questions/31948521/building-error-using-cmake-cannot-find-lpthreads

If you're still stuck... post what you tried and how you were able to narrow it down further.

**Comment by stanathong** [comment]
Thanks very much for your reply. I have the issue solved already and will close this issue after this. Yes, as you said it wasn't a bug of CamOdoCal, and I could successfully run it on VirtualBox without CUDA. I'm not sure what had solved this issue either falling SuiteSparse back to version 4.2.1 or installing OpenCV with the contrib module. I also wrote a note for installing dependencies/build packages on Ubuntu 14.04 and compiling CamOdoCal on VirtualBox for dummy if anyone needed.

Thanks again!

**Comment by ahundt** [comment]
If you have improvements to the installation notes, could you put them into the README.md in the appropriate place and submit a pull request? https://github.com/hengli/camodocal/blob/master/README.md

**Comment by stanathong** [comment]
It's a set-up procedure for dummy who doesn't have expertise in Linux system like me. I have this procedure written in MS Word and PDF and I'm willing to share. I rather can send you this file so you may place it at an appropriate place in the folder. Please let me know.

I can even help out summarize about the input format and running procedure for extrinsic calibration once mine is successful.

Thanks,
Supannee
